name: Server Monitor CI/CD

on:
  push:
    branches: [ 'deploy' ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ssh dev pm2 stop server-monitor
    - run: npm i
    - run: npm run build --if-present
    - run: ssh dev pm2 start server-monitor